### ISSUE TITLE
GoIV doesn't show button if starting on pokemon screen

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#437] opened 2016-09-18 22:07 UTC
Happening with the latest code.

1. Start Pokemon Go without starting GoIV service. 
2. Go to a Pokemon screen.
3. Go to GoIV, make sure "Launch Pokemon Go" option is enabled. Start the service.
4. Go back to Pokemon Go.

The button does not appear until the screen is pressed. If the "Launch Pokemon Go" option is enabled, it should do a first capture to check if the user has started GoIV while having a pokemon already selected. Minor issue since any touch will force the button to appear.

**Comment by DJCrapsody** [comment] 2016-09-18 22:41
This is because we don't periodically scan the screen but only scan the screen on touch. This is kinda annoying for me as well tho but it isn't breaking any functionality for now.

**Comment by Blaisorblade** [comment] 2016-09-20 01:43
Thanks for the reminder, we should make this very clear on the changelog. The battery savings are big but yes, this is a problem.

However, we *could* think about checking the screen a while after start, if "Launch Pokemon Go" is enabled. I know how.

**Comment by sarav** [comment] 2016-09-20 05:47
See comments in the PR. I'm actually kinda open to marking this as "won't fix". IV button not showing up in some pokemon screen is going to happen once in a while and we just have to educate the users.

For example, it won't show up for a post egg hatching or a post evolve Pokemon screen either. I just do the scroll up gesture again and the button comes back and I move on.

**Comment by Blaisorblade** [comment] 2016-09-20 11:36
Granted we should document this, we could either still merge the PR, or avoid merging so this behavior can trigger more often. What do you think @rpgrca @DJCrapsody ?

**Comment by DJCrapsody** [comment] 2016-09-20 11:40
From the user's standpoint, it comes back to "it should work why doesn't it?"
So I suggest educating the users in a way, through toast (as suggested in the other issue) and if required, in FAQ.

The "hacky fix" should not be used, I've actually had lesser black screens after the change.

**Comment by Blaisorblade** [comment] 2016-09-20 11:41
> The "hacky fix" should not be used, I've actually had lesser black screens after the change.

"lesser black screens"? You mean more ones?

**Comment by DJCrapsody** [comment] 2016-09-20 11:42
Ugh Gitskario comment editing is unreliable, always doesn't go through. I edited my comment.

**Comment by Blaisorblade** [comment] 2016-09-20 11:47
I still don't follow at all. The "hacky fix" is not to fix black screens but this issue (and my worry there might have been a red herring). Does that fix *cause* any problem?

**Comment by DJCrapsody** [comment] 2016-09-20 11:47
Scanning when the game is resuming is possibly the issue for black screen. on touch scan does not trigger scanning when resuming the game, therefore actually getting lesser black screens.

**Comment by rpgrca** [comment] 2016-09-20 17:00
When we (company) release a new version of the software we make a list of known bugs for which workarounds exist. This one would qualify as one, and so if there's enough documentation available it should work.

I still get black screens maybe 30% of the times I launch GoIV, but already got used to that.

**Comment by Blaisorblade** [comment] 2016-09-20 17:36
We're discussing documentation in #452—https://github.com/farkam135/GoIV/blob/master/CHANGELOG.md#features

FWIW right now this is a feature, not a bug; I'm also uneasy but it seems worth it, once you know.

**Comment by Blaisorblade** [comment] 2016-09-21 20:08
Closing in favor of #452.

**Closed by Blaisorblade** 2016-09-21 20:08 UTC
