### ISSUE TITLE
Crash when scanning screenshot from another Android/iPhone phone

### ISSUE THREAD

**Issue by NightMadness** [farkam135/GoIV#463] opened 2016-09-22 15:42 UTC
Hi Team,
A friend of mind send me a screenshot from an Iphone to check IV, I open the text message, clicked on share then GoIV, GoIV crashed.
Took same screenshot, took a screenshot of the screenshot using google now, sent to GoIV, calculated successfully.

Could this be bug #420 ? 

I have a galaxy S7 edge, stock, not rooted.

Example screenshot that fails
![img951676](https://cloud.githubusercontent.com/assets/22281828/18755502/86adc5e2-80ba-11e6-887c-e49b8e1ee6ff.png) _Level 22 Cloyster_

also, in order to scan I must enable powersave mode, even if i share the screenshot using the android share button. is this a bug?

**Comment by DJCrapsody** [comment] 2016-09-22 16:47
AFAIK, screenshots that did not come from your device or random pictures of food will crash GoIV on the current release. (IIRC it was fixed in one of the recent commits, I can't remember). You can try building from the source and see if it works (aka GoIV ignores screenshot).

You have to enable Battery Saver mode and start GoIV Pokefly service in order to use the share. We will probably be implementing something to show that when someone tries to share a screenshot.

**Comment by NightMadness** [comment] 2016-09-22 16:52
Yep, source i tested is only a week old, will take latest and see if it still happens. Whats wierd is i can take screenshot of the screenshot to make it work. Maybe issue with issue boundaries?

I think we should allow scanning from share even if goiv is not "started" or in power save mode.

**Comment by DJCrapsody** [comment] 2016-09-22 16:54
ocr is only initialized when pokefly is started. I'll pull that to another issue.

**Comment by Blaisorblade** [comment] 2016-09-22 22:40
@NightMadness In general you might want to use master, we devs all run with that. (Yes it might have regressions but we try to keep `master` always working well, so let us know if something breaks there).

This is a bug fixed in ac3267978b9665a2ce39a528b0b1002c12b061de and will be in 3.2: sharing any screenshot through share (as opposed to Google Now) will crash GoIV. I'm sorry the original description in the commit was probably unclear and hard to find.

Logcat should show you it's just a NullPointerException—you get logcat output from Android Studio if you run the app with the phone connected to your USB port (if USB debugging is enabled). If you want to be effective you want to figure out how to set this up.

**Comment by Blaisorblade** [comment] 2016-09-22 22:42
Closing for now, but please let us know/reopen if my analysis is wrong.

**Comment by Blaisorblade** [comment] 2016-09-22 22:43
BTW, thanks for the report anyway, don't take "closing" as a rejection.

**Comment by NightMadness** [comment] 2016-09-23 02:58
Hi @Blaisorblade,  
The error I am getting is `java.lang.IllegalArgumentException: x must be < bitmap.width()`

```
09-22 21:28:29.000 2685-2685/com.kamron.pogoiv.nointernet E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.kamron.pogoiv.nointernet, PID: 2685
                                                                            java.lang.IllegalArgumentException: x must be < bitmap.width()
                                                                                at android.graphics.Bitmap.checkPixelAccess(Bitmap.java:1728)
                                                                                at android.graphics.Bitmap.getPixel(Bitmap.java:1680)
                                                                                at com.kamron.pogoiv.OcrHelper.getPokemonLevelFromImg(OcrHelper.java:139)
                                                                                at com.kamron.pogoiv.OcrHelper.scanPokemon(OcrHelper.java:379)
                                                                                at com.kamron.pogoiv.Pokefly.scanPokemon(Pokefly.java:1605)
                                                                                at com.kamron.pogoiv.Pokefly.access$1200(Pokefly.java:83)
                                                                                at com.kamron.pogoiv.Pokefly$11.onReceive(Pokefly.java:1645)
                                                                                at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                                at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                                at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:158)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by NightMadness** [comment] 2016-09-23 03:57
I rebuild using Master, I was able to replicate the issue, 

can this issue be re-opened?

**Comment by DJCrapsody** [comment] 2016-09-23 04:43
Are you building your master branch or the main master branch? You have 10 commits ahead, stash the changes and try again?

**Comment by NightMadness** [comment] 2016-09-23 04:48
Main branch. I created new folder, new project directly from goiv git and recompiled apk. 

I Checked the line number above, it should match to master.

**Comment by Blaisorblade** [comment] 2016-09-23 09:18
I assumed you could reopen it too. The next step will be to get a stacktrace.
Can you replicate the issue only with a screen from a different phone? Have you tried one from your phone?

**Comment by NightMadness** [comment] 2016-09-23 11:49
Was not able to reopen, thanks @Blaisorblade for reopening. I pasted the stacktrace above. Also I posted the bad iphone image above, you might be able to replicate the bug.

My own screenshot works, Only failed with iphone screen shot. I tried three difftent screen shot from an iphone, all failed. I think its a max width, max height issue not matching to iphone spec. I suspect the reason screenshot of a screenshot works is it resizes the image to full screen to match phone spec.

I glanced at the code, is max height and max width calculation based on phone or the screenshot? If this is the issue I guess easy solution would be to resize the screenshot image, but the I think the right solution is to move arc calculation to ocr helper and recalculate all variables for each screenshot (only for screenshot mode).

Let me know if you can replicate the bug.

**Comment by Blaisorblade** [comment] 2016-09-23 14:22
> I pasted the stacktrace above.

Thanks, that confirms your diagnosis—this overlaps with #420 (we don't know what happened with those users).

> I glanced at the code, is max height and max width calculation based on phone or the screenshot?

It's based on the phone—taking it from the snapshot is not easy though: we ask the phone for the size of the bars above/below, how do we get that info from a snapshot? I'm not even sure what should the size above be—maybe 0 because PoGo draws under the iOS notification bar?

**Comment by NightMadness** [comment] 2016-09-30 03:02
Hey Team,
Resize code fixes it, but hmm i'm not sure its the right solution and if it works for all scenarios.
what do you think?

Code for resize:
```
            if (displayMetrics.heightPixels != bitmap.getHeight() ) {
                bitmap = Bitmap.createScaledBitmap(bitmap, displayMetrics.widthPixels, displayMetrics.heightPixels,
                        false);
            }
```

Pokefly.java
```
    private final BroadcastReceiver processBitmap = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            Bitmap bitmap = intent.getParcelableExtra(KEY_BITMAP);
            if (bitmap == null) {
                return;
            }
            String screenShotPathRaw = intent.getStringExtra(KEY_SCREENSHOT_FILE);
            Optional<String> screenShotPath;
            if (screenShotPathRaw != null) {
                screenShotPath = Optional.of(screenShotPathRaw);
            } else {
                screenShotPath = Optional.absent();
            }

            if (displayMetrics.heightPixels != bitmap.getHeight() ) {
                bitmap = Bitmap.createScaledBitmap(bitmap, displayMetrics.widthPixels, displayMetrics.heightPixels,
                        false);
            }

            scanPokemon(bitmap, screenShotPath);
            bitmap.recycle();
        }
    };
```

**Comment by Blaisorblade** [comment] 2016-09-30 12:02
That part looks good, but should compare both height and width.

But there are still a couple of things that won't work so well I fear. Can you test how well the arc is aligned or if at least we recognize the level correctly (by comparing with Google Now)? A problem is that, without Google Now, we don't show the screenshot below the GUI, but at least we should detect the same level in both cases.

Also, can you try on some other snapshots—say, from issues here?

The code involved in arc level detection is hard to understand and test, so below I've written a summary of what I do understand.

### Comparing both height and width

The image should be resized if either height and width don't match. Android devices can have different display ratios, so two screens could have the same height and different widths. I'm not sure we'd OCR the right areas but there's little we can do.

Resizing in that case will prevent crashes; `OcrHelper` only expects the image size to be `displayMetrics`, you resize the image to fit that constraint, so that will work. Somewhere we use `rawDisplayMetrics` which can IIUC be different, but it looks like it's not used directly in `OcrHelper`, so no mismatch.

### Arc position and level detection

The only potential issue seems to be with detecting the level from the arc and with placing the red dot correctly.

The expected positions of the white dot on the arc (through `arcInit`, `arcRadius`, and `Data.setupArcPoints`), and to compute where to place the red dot.

The only tricky part in `OcrHelper` is `OcrHelper.getPokemonLevelFromImg`. That uses the expected positions of the white dot on the arc, saved in `Data.arcX` and `Data.arcY`. That's in turn initialized by `Data.setupArcPoints` from `arcInit`, `arcRadius`. Finally, `arcInit` and `arcRadius` are setup in `MainActivity.setupDisplaySizeInfo`. I don't fully get `setupDisplaySizeInfo` and IIUC it was written by @farkam135 after testing on lots of screenshots, so I've just carefully refactored it.

Moreover, to show the red dot at the right point we use `statusBarHeight` in `Pokefly`, and that might be off.

**Comment by Blaisorblade** [comment] 2016-09-30 12:03
> Also, can you try on some other snapshots—say, from issues here?

Forgot to point out: you'll need to know the player level of course, but we should have some.

**Comment by NightMadness** [comment] 2016-10-01 00:59
The red icon is off but calculation is right. 
![screenshot_20160930-081053](https://cloud.githubusercontent.com/assets/22281828/19010589/b5e6bf16-8750-11e6-9e1e-421b46350ccc.png)

**Comment by Blaisorblade** [comment] 2016-10-01 02:14
> Seems to be working

Not to be picky, but it doesn't seem to work well... are you saying that on the iPhone screenshots the correct level is detected? That looks weird, but maybe it's just because `statusBarHeight` is wrong (the iPhone appears to have a smaller bar).

In contrast, in the screenshots from #347 we're clearly not detecting the right level. Is there a way in your screenshot viewer to "scroll" the screenshots up, so that the empty area is at the bottom? That might work better.

Maybe this is better than nothing. It'd be nice if we could make this better. But adding, say, iPhone-specific code is probably hard and out of scope since most of us couldn't test that.

> Any other places where i can find screenshots?

I have nothing specific in mind, but for now these test cases are enough.

**Comment by NightMadness** [comment] 2016-10-01 02:57
Yeah iphone IV stats works correctly when I selected the right trainer level.
  
Also these screenshots seem to be an extreme example of extra wide screen. @DJCrapsody do you know the trainer level for those screenshots.

**Comment by DJCrapsody** [comment] 2016-10-01 03:02
if they're my screenshots, it'll be level 23. any screenshots not provided by me, I wouldn't know.

**Comment by NightMadness** [comment] 2016-10-01 03:13
Thanks, just tested with trainer level 23, it does real the text correctly but not the ARC.

**Comment by DJCrapsody** [comment] 2016-10-01 03:24
Because the screenshot isn't provided by me. I don't rememver providing any screenshots here till date. Everything's on discord

**Comment by sarav** [comment] 2016-10-24 07:13
This is such a niche issue that I think we shouldn't make the code more complicated just to handle this.

**Comment by Blaisorblade** [comment] 2016-10-25 09:01
My bigger motivation is not the original one—I'd like to get this fixed so we have a chance to do regression tests on the scanning code.

**Comment by sarav** [comment] 2016-10-26 03:32
@Blaisorblade good point

**Comment by Blaisorblade** [comment] 2016-10-28 10:24
I think this is only waiting for somebody to do a PR with @NightMadness's code — @NightMadness, would you be willing to try your way with Git again? Should be easier this time. 

And while that's not perfect because of the status bar might have a different size, dealing with that mismatch seems not worth it.

**Comment by NightMadness** [comment] 2016-10-28 12:15
Sure, ill work on it when i get back from work.

**Closed** 2016-11-05 10:25 UTC
Labels: bug
