### ISSUE TITLE
Standard Live-OCR mode unusable since Oreo

### ISSUE THREAD

**Issue by ravemir** [farkam135/GoIV#868] opened 2018-02-10 19:31 UTC
I have used the app on this phone since I got it on Nougat 7.1.2.

However, after the update to Oreo 8.0.0, I could not get the live OCR mode to work properly for more than a couple seconds, not even being able to read a single appraisal, before GoIV becomes unresponsive, ultimately force closing.

I am using a Xiaomi Mi A1, with stock Android.

**Comment by ravemir** [comment] 2018-03-11 19:36
It looks like I'm not alone, albeit with a different phone (and sometimes different OS version, as some are reporting this on Nougat):
https://www.reddit.com/r/GoIV/comments/7ld19a/f
reezing_since_latest_update/?utm_source=reddit-android

**Comment by lramati** [comment] 2018-03-15 10:56
I've been using this on my Pixel 2 since I got it, and I've never had problems, so the issue probably isn't inherent to Oreo

**Comment by nahojjjen** [comment] 2018-03-18 13:33
Okay, so there's probably some issue that we need to find, but it does not seem to be 8.0.0 that's causing it.

**Comment by danibram** [comment] 2018-04-02 13:54
The same here with Huawei p10plus just updated to Oreo.
Running well on Nougat

**Comment by Reedyn** [comment] 2018-07-16 06:44
Same issue on Moto Z Play on Oreo

**Comment by nahojjjen** [comment] 2018-07-16 10:41
This thread currently indicates that there's an issue, but no information on what could be causing it; there was a hypothesis that it was caused by android 8.0, which has been debunked.

Is there any other information you could add on why it's not working?

In what way is it not working? Does the application instantly crash? Does it not start?

**Comment by jimmywan** [comment] 2018-07-25 23:23
FWIW, this wasn't working for my Samsung Galaxy S8 at some point and then it started working with a later release.

**Comment by ravemir** [comment] 2018-08-10 11:12
@nahojjjen I have captured a locgcat dump around 2 weeks ago, while using the OCR feature. You can find it [here](https://www.dropbox.com/s/klnh56tragmmuku/goIV-OCR.log?dl=0). This was done using Android 8.1 on a Xiaomi Mi A1.

Just did a quick test with the OCR feature turned on, yet again, but the result's still the same, so it was not fixed on my end. Anything else I can do to help track down what's going on?

**Comment by ravemir** [comment] 2018-09-05 12:04
Ok, new info: version 4.1.2 works flawlessly (apart from not recognising Alolans, but that's expected), with OCR blazing away.

Looking at the changelog for 4.2.0, the only thing that would make me suspicious is "Updated libraries", but none of the libraries changed on [this commit](36ee871eadc44d94ca3d208f87eb48ee32885bb1) look remotely related to anything OCR, nor platform specific.

Any ideas, @nahojjjen? [More people](https://www.reddit.com/r/GoIV/comments/9cga98/auto_appraisal_very_slow_on_huawei_p8_lite_2017/) are bumping into this, as well.

**Comment by ravemir** [comment] 2018-09-05 13:04
Erm, I don't know what happened, but somehow, I installed the latest version from Google Play and it is magically solved. I was wondering if it would load the data from my first installation, but I had to input my level/team/clipboard, as well as recalibrate before starting.

I suggest everyone still having the problem install the version from the store to assess if it is also solved for them.

**Comment by thearaks** [comment] 2018-09-06 08:04
@ravemir Very glad to hear that!
Actually, yesterday, I've tried the latest version on a friend's phone (Xiaomi Mi A1 with the latest Android 8.1 firmware) and didn't experience any crashes.
Hope that the problem is solved for the other users too!

**Comment by ravemir** [comment] 2018-11-20 09:49
Been using it for quite a while now and no issues to report on this front. Close it?

**Comment by nahojjjen** [comment] 2018-11-20 18:22
Thanks for following up on your issue report.

Yea, I think we can close this - we don't know how it got solved, but it doesnt seem to be a problem anymore.

**Closed by nahojjjen** 2018-11-20 18:22 UTC
