### ISSUE TITLE
Don't associate pokemon name with custom name on cancel

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#295] opened 2016-08-30 02:30 UTC
1. Rename a Rattata as Raticar.
2. Open GoIV, pokemon name is recognized as "Raticate" in red.
3. Cancel.
4. Reopen GoIV, pokemon name recognized as "Raticate" in green.

Pressing Cancel should prevent GoIV from associating Raticar with Raticate. One should assume the pokemon name has been correctly guessed only if the user presses "Check IV" instead.

**Comment by sarav** [comment] 2016-08-30 16:32
I know why this happens and where the code changes should move to. I just don't know where that code actually is on the files.

The code where I store the usercorrections needs to be moved into the "on Click" event of the spinner or whatever event fires when the user actually clicks it. I don't know how to use Butterknife or even find the spinner in some layout to add an onWhatever event to it.

But it shouldn't be happening for the cancel path though. I don't think the code to store it would have been executed!

**Comment by Blaisorblade** [comment] 2016-08-31 00:17
@sarav looking at the code, I think this is due to `cachedCorrections` rather than `userCorrections` (which you're IMHO hinting at). I tried to address the TODO in #313.

Indeed, if you restart GoIV the recognized text is red again.

When I reproduce this, Step 4 means "press the IV button again".

**Comment by sarav** [comment] 2016-08-31 02:02
I think I might have hacked up the userCorrections to work around the point I made when I made the commit to save it. I still think it needs to go into some event Listener method.

**Comment by Blaisorblade** [comment] 2016-08-31 10:47
> I think I might have hacked up the userCorrections to work around the point I made when I made the commit to save it. I still think it needs to go into some event Listener method.

Failed to parse, but I hope #313 addresses that.

**Comment by sarav** [comment] 2016-08-31 16:36
Actually, I knew that the match distance goes to 0 (confident match) if we cache it. The reason I let that happen is that "if the user sees the guess and doesn't correct it, then that's an implicit okay from the user. So the app is more confident the next time that it got the guess right"

So, Raticar and Raticate-80/90 would both be guesses as Raticate by the app. If the user "Check IV" for Raticate-80/90, then the app will be confident Raticate-80/90 is Raticate the next time. But if the user opens "Raticar" and doesn't "CheckIV" it should be just as "not confident" as before.

The issue reported is that we are doing that even if the user chose not to "Check IV". We can fix that my moving this caching into where user corrections are cached too. But that'll mean the distance calculation would be done each time the user opens a Pokemon, but hits cancel -- but that's hopefully not too often.

I don't have a strong preference between what I said above and what @Blaisorblade has done. So, either is fine by me.

**Closed** 2016-08-31 18:15 UTC

**Comment by Blaisorblade** [comment] 2016-08-31 18:17
I merged the existing PR for now. It would be good to rationalize and fine-tune this later, I also had ideas here:

https://github.com/farkam135/GoIV/pull/313#issuecomment-243731551

But I don't want to do that in a rush.
