### ISSUE TITLE
Black app screen in PoGo after starting GoIV

### ISSUE THREAD

**Issue by voltaek** [farkam135/GoIV#424] opened 2016-09-18 00:17 UTC
After starting the GoIV service, PoGo is completely black and unresponsive when switched back to, and must be restarted to use. I've tried to figure out a consistent way to make this happen, but I can't seem to find one. I think it only seems to occur when PoGo has been open for awhile, and it doesn't seem to matter whether it's manually or automatically switched to after starting the GoIV service. I'd initially turned off the auto-switch, but I just had the black app screen again, so I don't think it's related to that.

**Comment by DJCrapsody** [comment] 2016-09-18 01:22
Has been answered multiple times, the black screen is caused by PoGo being developed on Unity Engine. Sometimes it works, most times it doesn't. Just restart PoGo and it's fine.

**Comment by voltaek** [comment] 2016-09-18 01:42
I looked through other issues and didn't see anything like this. Since this is a common thing, I added a question to the FAQ section on the README in a PR.

**Comment by DJCrapsody** [comment] 2016-09-18 01:52
That's good. Can you add a 'Fix 424' at the end of the PR? So closing the PR would close the issue too.

**Comment by voltaek** [comment] 2016-09-18 02:01
Is that an automatic thing or just so the person doing the merge knows to also close the issue?

**Comment by DJCrapsody** [comment] 2016-09-18 02:01
It's automated

**Closed** 2016-09-18 02:07 UTC

**Comment by voltaek** [comment] 2016-09-18 02:08
Is there any particular syntax required? I don't see anything about this in the PR section of CONTRIBUTING.md. Might be good to add the specifics there.

**Comment by DJCrapsody** [comment] 2016-09-18 02:11
I could probably add it into CONTRIBUTING, unless you would like to volunteer to do it?

Article here: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by voltaek** [comment] 2016-09-18 02:13
Oh okay, I see, it's a GitHub specific thing. Yeah, I can put something together to add to CONTRIBUTING.

**Comment by DJCrapsody** [comment] 2016-09-18 02:14
Yes it is. That'll be great 👍
