### ISSUE TITLE
keyboard wont exit when Checking IV (if not pressing done button)

### ISSUE THREAD

**Issue by NightMadness** [farkam135/GoIV#498] opened 2016-10-01 06:38 UTC
To replicate:
1. Click on Text like CP/HP/Candy.
2. Don't click on DONE button on the keyboard.
3. Click on "CHECK IV".
4. clicking on DONE on keyboard does not hide the keyboard
![screenshot_20160929-080158](https://cloud.githubusercontent.com/assets/22281828/19012311/5bb40d8a-877f-11e6-8d10-9d9c3b7f5056.png)

**Comment by Blaisorblade** [comment] 2016-10-02 19:22
IIRC the only one getting that magic up to now is @oskomonzon... maybe @thearaks has insight?

**Comment by oskomonzon** [comment] 2016-10-03 13:34
I'll take a look at it later today. Should be an easy way to fix it.

**Comment by thearaks** [comment] 2016-10-04 07:57
I think it's caused by the the focus that insist on a (hidden) view.
When we show the result screen we should also move the focus to something else, so the keyboard will close (at least, it should!).

If this won't work we can close the soft keyboard programmatically:
`InputMethodManager imm =  (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
imm.hideSoftInputFromWindow(view.getWindowToken(), 0);`

**Comment by oskomonzon** [comment] 2016-10-04 11:28
Closing it programmatically sounds less hacky, so I'd go with that.

**Comment by nahojjjen** [comment] 2016-11-15 12:01
Tried to solve this in #555

**Comment by nahojjjen** [comment] 2016-11-17 21:04
... solved in #555

**Closed** 2016-11-17 21:05 UTC
Labels: component: gui
