### ISSUE TITLE
Galaxy Note 3 level arc misaligned

### ISSUE THREAD

**Issue by fredkilbourn** [farkam135/GoIV#150] opened 2016-08-23 13:02 UTC
Hey I have a Galaxy Note 3 and the level arc is a little bit misaligned, enough to cause false readings at my current level (27).

This is what is detected (lvl 28 mon):
![screenshot_2016-08-23-07-49-26](https://cloud.githubusercontent.com/assets/658757/17892500/34a265ca-6907-11e6-9550-fc024b384412.png)

This is what is accurate (lvl 28.5 mon):
![screenshot_2016-08-23-07-49-30](https://cloud.githubusercontent.com/assets/658757/17892502/38048ef0-6907-11e6-9f11-58de093e80fe.png)

Notice that both dots aren't aligned properly but the correct one is further misaligned.  Not sure what needs to change in the code but the whole overlay needs to be shifted vertically slightly I think.

**Comment by Remiscan** [comment] 2016-08-23 14:15
I think I know why this happens!

At level 1, the white dot is centered where the level arc starts. But at max level, it is not centered where the level arc ends! (but the red dot from GoIV is). Take a look a these pictures to understand what I mean:

http://imgur.com/a/BRNUP

This could be the cause of most misalignment issues, don't you think?

**Comment by max1c** [comment] 2016-08-23 22:53
Galaxy S7 Edge had this problem for past 2-3 versions. It's extremely annoying to deal with because I never know which reading is the right one. It's always either bellow or above the dot.

**Comment by Blaisorblade** [comment] 2016-08-25 02:01
I'm marking this as duplicate of #175 to track all "arc issues" together.

**Closed by Blaisorblade** 2016-08-25 02:01 UTC
Labels: duplicate
