### ISSUE TITLE
Ditto scanning detects Hitmonchan

### ISSUE THREAD

**Issue by DomiEncore** [farkam135/GoIV#596] opened 2016-11-29 18:37 UTC
When scanning a renamed Ditto it alwas detects Hitmonchan for me.
![screenshot_20161129-192717](https://cloud.githubusercontent.com/assets/24255184/20723526/2de95994-b66b-11e6-88d8-ffde60f4b342.png)

**Comment by nahojjjen** [comment] 2016-11-30 20:15
I cant seem to reproduce this issue, do you have any other specs or details which you think might affect the scan?

**Comment by Nincodedo** [comment] 2016-12-03 06:44
I also get this issue but it resolved to Golbat instead. I am using version 3.3.1 of GoIV from the Play store. I have a Nexus 5X running Android 7.0. Please let me know if you need additional information.

![screenshot_20161203-002817](https://cloud.githubusercontent.com/assets/436953/20857418/6dc5f382-b8f1-11e6-8e7b-54bee21e90df.png)

**Comment by nahojjjen** [comment] 2016-12-03 11:22
@Nincodedo Your issue seems different- the entire scan failed for you. (except cp) so it probably did not receive information which it could use to guess the pokemon species. In OPs case the scan seemed to succeed, which indicates the it did receive information, but could not handle it correctly.

**Comment by Nincodedo** [comment] 2016-12-03 18:47
Gotcha. Would you like me to create a new issue for my case? I can get this to happen pretty regularly with a variety of pokemon.

**Comment by nahojjjen** [comment] 2016-12-03 19:13
@Nincodedo Do you have the option to hide/show the navigation bar on your phone? Make sure that the navigation bar has the same setting for GoIV and Pokemon Go. Also make sure that there are no applications that alter the screen content such as overlays or screen tinting applications.

**Comment by Nincodedo** [comment] 2016-12-03 19:21
I do not have the option to hide/show the navbar and I have no other overlays. This only happens when using screenshots to calc IVs. The screen capture works perfect.

**Comment by nahojjjen** [comment] 2016-12-03 19:26
That's quite odd- I believe both screenshots and screen-scanning call the same scanPokemon method, so I suppose the screenshot method fails to initialize the screen settings correctly?

If you've got a reliable way of reproducing the issue on your device, please create a new issue detailing steps and the issue. :)

**Comment by nahojjjen** [comment] 2016-12-14 17:30
As for the original issue, we can see that there's a scan error.

We don't know why, and we cant reproduce the issue. I'm going to close this issue, but I'll reopen it if more info is received / more people experience the issue.

**Closed by nahojjjen** 2016-12-14 17:30 UTC
