### ISSUE TITLE
LG G3, CP arc misalignment

### ISSUE THREAD

**Issue by Wachu** [farkam135/GoIV#87] opened 2016-08-19 15:51 UTC
Tried to manually adjust the arc but it's not aligning correctly
https://s4.postimg.io/ouxhmiqu5/Screenshot_2016_08_19_23_43_06.png
https://s4.postimg.io/w9mtewcpp/Screenshot_2016_08_19_23_43_00.png

1440 x 2560
Android 6.0
Battery saver is off
Player level is correct (Level 12)

**Comment by farkam135** [comment] 2016-08-19 17:20
What's your trainer level?

**Comment by Wachu** [comment] 2016-08-19 19:38
trainer level 12

**Comment by Wachu** [comment] 2016-08-20 18:15
Another screenshot for the arc. MY Trainer level is now 13 for these screenshots. I saw the other issue thread about the arc issues and thought you might need more info.

automatic alignment
https://s3.postimg.io/ydch7mcqr/Screenshot_2016_08_21_02_07_25.png

Manual alignment ( this is probably the correct value. I check the IV stats using pokeassistant site and this is the similar result)
https://s3.postimg.io/6byftx7gj/Screenshot_2016_08_21_02_07_14.png

Pokemon Stats
Name : Nidoran♀
CP : 233
HP : 49
Dust : 1300
Powered Up : No

**Comment by farkam135** [comment] 2016-08-23 22:07
Closing, duplicate of #70, am working on improving the arc!

**Closed by farkam135** 2016-08-23 22:07 UTC
