### ISSUE TITLE
Temporary Bloat Clean

### ISSUE THREAD

**Issue by farkam135** [farkam135/GoIV#162] opened 2016-08-23 21:57 UTC
GoIV is getting pretty fragmented and bloated so let's clean some stuff up before the redesign. Below is a list of everything that should be high priority (visual changes). If anyone objects to any of these changes let me know, but please realize this is only temporary changes until the redesign and it's going to be hard to change my mind on these:  

- [ ] Shorten instructions to allow more room for 480p devices
- [x] Round ALL percentages (min/avg/max)
- [x] Possibilities, show only Min and Max combinations and then the number of total possibilities below. 3 Lines total! (if only 1 more possibility show it as well)
- [x] For evolution CP show it at current level not max level.
- [ ] Make CP/HP move up when keyboard opened (works for some devices)  
I'll be adding to this list as new things need to be adjusted.

**Comment by sarav** [comment] 2016-08-24 06:49
1. What redesign?
2. So, this checklist the stuff that's considered "bloat"? As in UI bloat? Or these are the things that need to be done before the redesign?

In any case, I think the code needs some refactor and clean up to make it more friendly to code. Here are some suggestions:

0. Run some autoindenter on the whole time and make one single commit. That's make the rest of the steps more readable and manageable.
1. Move the pokedex and pokemap from PokeInfoCalculator. Those two have nothing to do with just calculations any more. If anything, we should move them into static variables in Pokemon.java or create a Pokedex.java
2. getPossiblePokemon should be part of Pokemon.java
3. All the OCR analysis code should move to something like OCR.java or PokeOCR.java. And maybe even make it a singleton class. The constructor could do the tesseract init, the arcpoints calculations, etc
4. Pokefly wouldn't need to send intents back and forth between MainActivity and Pokefly to process screenshot then.
5. Probably move any other remaining Intent receivers into Pokefly
6. Delete all the useless comments of code. That's actually bad style when using git. Bring back old code is what git revert is for.

I can work on some of these, but I wouldn't work on it without some consensus on what the people working on the refactor are going to do. Otherwise, we'll have a ton of wasted effort from merge conflicts.

**Comment by jehy** [comment] 2016-08-24 09:10
Reformatting commit is a good one. Better to do make it when @farkam135  is online to avoid merge conflicts.

**Comment by Blaisorblade** [comment] 2016-08-25 01:56
Agreed on the reformatting—we just need to minimize conflicts, probably by deciding on the open PRs. For the rest I see lots of sensible ideas but I haven't looked in detail.

Regarding intents back and forth: I also find them confusing, but this is less obvious to me—moving code across them is not a simple refactoring. For instance, a service can run in the background, unlike an activity. But frankly this requires a deeper knowledge of Android APIs than I have yet (I just get the basics).

**Comment by sarav** [comment] 2016-08-25 03:39
I think I have a decent idea of it. No expert by any means. But having an Activity scan for images is definitely not right. Btw, when I was doing profiling, the intents were taking a lot of time (sure tracing isn't accurate, but it seems proportional) because of all the packing and unpacking that goes on with Intents. If it can be a stateless function call, that's what we should use.

**Comment by Blaisorblade** [comment] 2016-08-25 18:30
My personal refactoring preferences:

- start with refactorings that can't change internal behavior, so that the code gets more readable before we do the hard changes. To be sure: simplifying the intent flow will probably make things better, but it's trickier to get right.
- separate functions that can be unit-tested. For instance, for all the manipulations on strings after the OCR can be tested so we can notice regressions if we change heuristics.
And generally, I'm happier merging refactorings if there's a testing suite checking stuff.
- if pieces of code must coordinate to avoid bugs, create abstractions around them—like the methods in https://github.com/farkam135/GoIV/pull/164/commits/61a004d0659ccff2b6f138018042f740a20684d7 (you could actually encapsulate that with a bit more code, but I left that alone).

**Comment by sarav** [comment] 2016-08-25 18:34
Now that the code reformatting is done, I'll try the intent refactoring.

**Comment by nahojjjen** [comment] 2016-08-26 22:02
The problems this issue was trying to address was fixed by the UI upgrade

**Closed by nahojjjen** 2016-08-26 22:02 UTC
