### ISSUE TITLE
Toasts not displayed 

### ISSUE THREAD

**Issue by Christian-X** [farkam135/GoIV#692] opened 2017-07-05 08:06 UTC
The Toasts that should be displayed (Content of Copy to Clipboard, QuickIV) are not displayed for me

Phone: Honor 8, Android 7.0 Nougat, EMUI 5.0

**Comment by TripSixes** [comment] 2017-07-05 15:45
I think nahojjjen replied on a reddit comment about this.. but adding here too.

Please indicate whether you are using Screenshot mode or not.
Are you seeing "any" toast when the GoIV "IV" button appears on screen? (failed to scan, etc)
Is the IV button showing up after viewing a pokemon detail screen?
Lastly, knowing your exact settings config may also help narrow down what is the cause.

**Comment by Christian-X** [comment] 2017-07-05 16:51
I'm not using screenshot mode.

I don't see a single toast issued by GoIV (i think the configuration option to display the String copied to the clipboard is a toast as well, i don't see that). No Scan Failed as well.

The IV Button is showing up ~0.5Seconds after i change to the detail screen, it works great. Scanning of the appraisal works as well.


Settings:

Start Pokemon go - true
Confirmation - true
Expanded appraisal opened by default - false
show translated monster name - false
copy to clipboard - true
copy differently on single result - true
show clipboard preview popup - true (not working)
Show how many you can evolve - true
auto appraisal delay - 300ms
show quick iv preview - true
show custom clipboard in quick iv - true (tried with false as well)
Use screenshots - false
automatic update - false

**Comment by TripSixes** [comment] 2017-07-05 22:20
As an FYI.. a user on Reddit just shared that he too was not seeing any of the toast notifications from GoIV.  He then realized that he had previously restricted the notification level of GoIV, which seemed to also affect the toasts.  Can you check to see if you might have previously changed anything in this area?

Thanks.

**Comment by nahojjjen** [comment] 2017-07-06 09:39
Some more info: 
The method that calls for the IV button to show in the left corner is the same method which calls for the toast to appear, if you're seeing the IV button but not the toast, there's probably something strange with the Toast settings/permission.

**Comment by Christian-X** [comment] 2017-07-06 12:12
The IV Button is a popup window, isn't it?

I've seen the coupling between notifications & toasts, from what i can see i've enable all options (and get the permanent notification stating GoIV is running...)

**Comment by urinella** [comment] 2017-07-06 12:56
Hi, I'm the one who made the comment on reddit (under update post).

I found something:
![image](https://user-images.githubusercontent.com/21242355/27911906-21386d6a-625b-11e7-9ecb-179c59cd216c.png)

If you switch from Pokemon screen to IVGo very fast you'll see the toast sometimes. But not indie PokemonGo itself.

(Huawei P9 - lite, Android 7, Emui 5.0)

**Comment by Christian-X** [comment] 2017-07-06 13:11
@urinella thanks for that idea - i can confirm that. I'll be able to see the toast inside GoIV, but not inside pokemon go.

Seems to be some Emui (5.x?) limitation/"feature"/bug ...

**Comment by TripSixes** [comment] 2017-07-07 00:05
I've found reference to this issue on an xda-developers thread.  Unfortunately there is no solution mentioned.  I have replied to the thread to see if the original poster ever found out why this was occurring and if there was a work-around to make it work.

Thanks to you both for connecting the dots so that we could narrow down the reason.  Will update you all if I hear back.

**Comment by TripSixes** [comment] 2017-07-14 17:50
Just a quick update.  Latest development plans are to move away from using the Toast for this feature and instead simply update a layout/overlay near (or within) the IV Button space.  Once this feature is ready for release we should be able to close this issue since it will no longer be applicable.
Stay tuned.

**Comment by nahojjjen** [comment] 2017-09-29 21:34
Closing this issue, as the quick IV information is not shown as a toast anymore.

**Closed by nahojjjen** 2017-09-29 21:34 UTC
