### ISSUE TITLE
Crash Samsung S6 Edge 

### ISSUE THREAD

**Issue by Snozzedem** [farkam135/GoIV#701] opened 2017-07-20 02:37 UTC
Hi. 
I've just downloaded the newest Goiv (3.5.0) and when pressing start button Goiv crashes and i get a popup 'System UI has stopped. Open app again'. 
All permissions have been granted for Goiv, and no obvious reasoning what's causing the app to crash. 
This happens using both online and offline Goiv. Using app from clean install and custom edit. Also installed later version (3.4.5) with the same issue. 

I'm using a Samsung S6 Edge 925I
Build v - NRD90M.G925IDVU3FQD1
Running Nougat 7.0.

**Comment by nahojjjen** [comment] 2017-07-21 08:46
Have you tried restarting the phone?

Also try running in screenshot mode to see if it's related to the screen api.

**Comment by nahojjjen** [comment] 2017-09-30 15:02
Since several crashfixes have been released since 3.5.0, and we dont have clear reproduction-steps for this issue, im closing it. Feel free to open a new issue with more details if the problem persists.

**Closed by nahojjjen** 2017-09-30 15:02 UTC
