### ISSUE TITLE
Add Notification Action Buttons

### ISSUE THREAD

**Issue by voltaek** [farkam135/GoIV#268] opened 2016-08-28 22:42 UTC
Adding an embedded action button within the GoIV notification to stop and start screen capture would be a nice alternative to having to switch back and forth between the PoGo and GoIV apps. This way when a user taps Stop from the notification, the notification could stay in their notification list while they are doing other things in PoGo, then when they're ready to scan things again they can just tap Start on the notification button. Alternatively, if they're all done, they could just swipe the notification away after tapping Stop (I think you'd want to continue preventing swiping it away while still running, as it do currently). To be clear, this would be just one button that they'd tap to toggle screen capture, and the text would just change from Start to Stop.

This is an alternative to #263, the always-displayed floating button suggestion, where I suggested that screen scanning only runs for a moment when the button is tapped. If that idea is not done, this seems like the next best way of easily limiting the time that your screen is being continuously scanned.

Outside of anything relating to toggling scanning, I'm sure there are other things users could use action buttons for.

**Comment by Paxtez** [comment] 2016-08-28 23:12
Would this be a duplicate of #30?

**Comment by Blaisorblade** [comment] 2016-08-29 17:17
@Paxtez yes but this issue has a better description.

Personally, I'd like we'd need keys to:
- start Pokefly
- stop Pokefly
- I'd love increase trainer level by 1 (every other change can be done via the GUI, that's the only one that is a bit annoying)
- something to close the app when Pokefly is stopped and the notification is dismissed.

Technically, notification actions require intents mostly, so this relates to #278 and the intent flow a bit. Now that other stuff was cleaned up, it should be at least possible to try.

**Comment by rhari991** [comment] 2016-08-29 17:48
I'd like to work on this if nobody is currently doing so.

**Comment by Blaisorblade** [comment] 2016-08-29 17:57
Didn't really start—assigning to @rhari991.

BTW: the one thing I did figure is that we might need to switch from Notification to [NotificationCompat](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#addAction(android.support.v4.app.NotificationCompat.Action)) if we need APIs like [addAction(Action)](https://developer.android.com/reference/android/app/Notification.Builder.html#addAction(android.app.Notification.Action), since that requires API level 20 but we support 19.

**Comment by rhari991** [comment] 2016-08-29 18:01
Thanks, will add that in.

**Comment by Eccenux** [comment] 2016-08-29 20:52
> something to close the app when Pokefly is stopped and the notification is dismissed.

You can do that from recent apps. Closing GoIV from there is stopping the service and ends GoIV.

**Comment by Blaisorblade** [comment] 2016-08-29 21:22
> You can do that from recent apps. Closing GoIV from there is stopping the service and ends GoIV.

Thanks, till now I've always stopped the app first before going to recent apps.

Still that reminds me: why do tens of users on Reddit say they need to reboot their phone and Pokemon Go and X and Y and Z when the IV's button gets stuck? Did they all miss this? A few times I told them to close the app from recent, but it didn't work for them.

(Then again, it's not clear the notification action would work).

Back to the main issue: a button in the notification might still be more discoverable.

**Comment by Blaisorblade** [comment] 2016-09-10 12:21
Scheduling this for 3.3—this might go in earlier given a working PR that is safe to merge (say, a new version of #371 from @thearaks), but this might not be easy.

**Comment by Blaisorblade** [comment] 2016-09-12 21:40
@rhari991 Just saw again you had volunteered for this (I had forgotten). Did you make any progress? If you want to work on this, you might want to look at #371 from @thearaks.

Meanwhile, note that #263 could avoid this need; to my ignorant eyes it seems harder to implement though.

**Comment by thearaks** [comment] 2016-09-12 22:34
@Blaisorblade, @rhari991 take a look at #404, it's my latest PR on this issue. It could be a starting point for a "+1 level" notification action, if it gets merged!

**Comment by rhari991** [comment] 2016-09-13 08:25
@Blaisorblade I completely forgot about this, sorry ! My schoolwork has been keeping me busy the past few days. Seems it has been done.

**Closed** 2016-09-19 15:19 UTC
Labels: enhancement
