### ISSUE TITLE
Apparently Pokemon for L38 cap at L39

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#301] opened 2016-08-30 11:29 UTC
L38 player [mentioned](https://pokemongo.gamepress.gg/pokemon/127#comment-2808867626) pokemon [cap](http://imgur.com/a/mbX92) at L39 once he reached it (instead of L39.5). Something to keep in mind, looking for more information about this.

**Comment by Blaisorblade** [comment] 2016-08-30 12:50
That's... interesting. Levels beyond that *do* exist (https://pokemongo.gamepress.gg/power-up-costs), I guess they're just not reachable for a L38 player. Can you ask on one of the general PG subreddits (say, TheSilphRoad) where people with a clue hang out? Ideally we'd want to know what happens at levels 39 and 40—maybe you'll need to ask on PokemonGoDev since botters (who'd know right?) hang out there. (NOTE: I'm *NOT* encouraging bots).

**Comment by Blaisorblade** [comment] 2016-08-30 13:20
Assigning to 3.1.0, but this shouldn't hold up the release if we don't figure out the right formula in time.

**Comment by Blaisorblade** [comment] 2016-08-30 13:22
BTW can GoIV even tell the difference between those levels? I won't be surprised if the dot is too big.

**Comment by hlplulustg** [comment] 2016-08-30 15:40
@Blaisorblade Those screens would have no impact on trainer level cap, but pokemon max level. The powerup option is not removed from the detail screen if the trainer level is too low for leveling the pokemon (it is greyed out or gives an error, i dont remember). The cost formula stays correct.

**Comment by Blaisorblade** [comment] 2016-08-30 16:05
> Those screens would have no impact on trainer level cap, but pokemon max level. 

Sure sure. Sorry if I was ambiguous. But the formula for the arc position does use the pokemon max level, so it'd have to change—this change would imply at that trainer level the arc has one less possible position, hence all the positions should shift rightward.

> The powerup option is not removed from the detail screen if the trainer level is too low for leveling the pokemon (it is greyed out or gives an error, i dont remember)

Yep, it gives an error that we've seen elsewhere. Maybe the button disappearing is a bug, because they max is trainerLevel  + 1 rather than trainerLevel  + 1.5 and they use different code? I won't be surprised for such PG bugs.*

*A PG bug I reproduced, just to show they have silly bugs: sort pokemon by CP and level up a pokemon (which is say the 5th in the list, any position is good) so it changes relative position in the list (because it becomes more powerful than another). After powerup is completed, you'll be shown the new 5th (or n-th) pokemon.

**Comment by Blaisorblade** [comment] 2016-09-01 18:00
Postponing as no information has arrived and we're heading for release.

**Comment by Blaisorblade** [comment] 2016-09-10 12:23
Postponing again to backlog.

**Comment by rpgrca** [comment] 2016-09-20 01:07
Adding some extra information that might or not be relevant. Browsing pokemon-related pages I found [this](http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/571826-how-get-max-cp-dragonite.html) (referenced from [here](https://pokemongo.gamepress.gg/power-up-costs)).

It would seem that the powerup button disappears at L39, preventing common players from powering pokemon up to L40. However, they are able to power them up via the bot client (because it sends the power up command directly to the server). So, it would seem it's a visual bug, because the command is still enabled but you can't access it. Or they may have capped it on purpose (but forgot to disable the command itself).

**Comment by Blaisorblade** [comment] 2016-09-20 01:21
Thanks a lot—I had seen the ownedcore thread, but it's useful to know that even Gamepress didn't find better info.
Nonetheless, I suspect we should do nothing about this till we get a fuller clue from reports or at least one tester with the problem.
I'm especially worried about the arc formula, which uses the max level but for which we have no info.

I'd like to close the issue for now—if further input shows up we can reopen it. Still, again, your interest and efforts are appreciated.

**Closed by Blaisorblade** 2016-09-20 01:21 UTC
Labels: bug, component: logic, need confirmation
