### ISSUE TITLE
Staryu loops

### ISSUE THREAD

**Issue by TriXXeD** [farkam135/GoIV#51] opened 2016-08-17 14:43 UTC
Staryu seem to bug out the app, the toast with the string "scanning" is shown, but then nothing happens afterwards and another pokemon cannot be scanned untill you have restarted GoIV, i only had 5 staryus to check with but with 3 attempts on each i'm 15/15 with this loop.

**Comment by nahojjjen** [comment] 2016-08-19 11:28
I cant reproduce this issue, maybe it was fixed in an earlier patch?

If you can no longer reproduce this issue, I think it's safe to close.

**Closed** 2016-08-19 17:46 UTC
