### ISSUE TITLE
Upload on F-Droid

### ISSUE THREAD

**Issue by marsjaninzmarsa** [farkam135/GoIV#380] opened 2016-09-06 10:49 UTC
It's open source, so why not?

**Comment by Blaisorblade** [comment] 2016-09-08 09:52
We talked about it and were generally in favor, but nobody actually did it.

**Comment by Eremiell** [comment] 2016-09-21 05:44
Seems like currently only offline version would classify for F-Droid, as they don't allow auto-updates. Maybe we can get an F-Droid version with crashlytics (unless those break one of the rules as well and I missed it) but with aim to be updated through F-Droid (so no auto-update)?

[F-Droid base-line rules](https://f-droid.org/wiki/page/Inclusion_Policy)

**Comment by DJCrapsody** [comment] 2016-09-21 06:07
we can have 3apks
Online (updater and crashlytics)
Offline (no internet)
F-Droid (crashlytics only)

**Comment by marsjaninzmarsa** [comment] 2016-09-21 09:18
GoIV online doesn't have auto updates, it have only prompt "new version is available, you can download it and install manually from this link", I think that this is totally acceptable.

**Comment by Blaisorblade** [comment] 2016-09-21 16:51
Not quite, we have a prompt and if you confirm we do the entire download and install. Would that be OK? @marsjaninzmarsa do you have a pointer to the F-Droid rules?

We could have the no-uploader variant if needed, it's just a slight nuisance.

**Comment by marsjaninzmarsa** [comment] 2016-09-21 23:31
If you have a prompt, it should be OK, I believe.

**Comment by DJCrapsody** [comment] 2016-09-22 07:40
> [15:30] <DJCrapsody> no I mean, if the app includes an updater that prompts the user to d

[15:30] <DJCrapsody> update the app, does it violate the inclusion policy?

[15:32] <krt> not really, but i'd rather have the app build reproducible then. so we could re-use upstream signature,  because users wont be able to upgrade otherwise

**Comment by Blaisorblade** [comment] 2016-09-22 07:49
@DJCrapsody please provide more context?

**Comment by Blaisorblade** [comment] 2016-09-22 08:11
I've looked at https://f-droid.org/wiki/page/Inclusion_How-To#Source_Code, it seems they'd usually build it themselves so the auto-update would fail.

Anyway, this feature is tagged as "help wanted". To see progress, please actually submit the app. The offline version should be submittable as-is.

Here's how to actually get started:
https://f-droid.org/forums/topic/read-this-before-posting/

and basically they appreciate a Pull Request (er, Merge Request) to their repo according to these instructions:
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by nahojjjen** [comment] 2016-11-17 22:09
I'm going to close this, since the app is now easily accessible on the play store, which it was not when the issue was created.

If anyone feels like adding it to f-droid is something they'd wanna do, they're free to open a new issue or discuss it in the discord channel.

**Closed by nahojjjen** 2016-11-17 22:09 UTC
Labels: help wanted
