### ISSUE TITLE
Unable to set permissions as of trainer level 21

### ISSUE THREAD

**Issue by Korthalion** [farkam135/GoIV#923] opened 2018-05-26 08:49 UTC
Device is a OnePlus 5
First noticed on 25/05/18
Team Instinct

App worked fine yesterday until I levelled up from 20 to 21, then when I went to set the level on GoIV to 21 I found I was unable to start the screen reading part of the app.

Specifically the 'Start' button. The permission request box opens and I'm able to check the 'dont ask in future' box, and I'm able to click cancel and the box goes away. There is no visible invalidation on the start/accept button, but I'm unable to click it.

**Comment by nahojjjen** [comment] 2018-05-28 11:12
Does the problem persist after restarting the application?

**Comment by Korthalion** [comment] 2018-05-28 11:58
Yes I tried restarting everything. The issue went away once I levelled up
to 22.

**Comment by nahojjjen** [comment] 2018-06-06 21:31
Hmm, do you have any steps for reproducing the issue?

Without knowing how to recreate the issue / knowing more about the issue, solving it will be impossible.

**Comment by Korthalion** [comment] 2018-06-06 21:40
Not without starting an entirely new account and leveling it up to 21...
Just thought I'd let you know of the bug in case it happens to someone else

**Comment by nahojjjen** [comment] 2018-06-08 18:42
Hmm, okay. Ill remember this, but since we don't have any way of following up on the issue at the moment, I'll close the issue.

**Closed by nahojjjen** 2018-06-08 18:42 UTC
