### ISSUE TITLE
IV button not appearing on Umi Plus E android 6.0.1 

### ISSUE THREAD

**Issue by ANDresmar** [farkam135/GoIV#670] opened 2017-03-16 20:13 UTC
The iv button doesn´t apear in my phone, before i had it in a nexus 5 and there it works perfectly, but not in the Umi plus Exteme, i attach the screenshoot of the game, and also of the android version

it also has all the permisions given
i tried 2 different versions 3.4.0 and 3.4.1 none of them shows the button

![screenshot_20170316-210318](https://cloud.githubusercontent.com/assets/7078459/24016648/3e3f8900-0a8d-11e7-8094-a76f2baf3855.png)
![screenshot_20170316-210225](https://cloud.githubusercontent.com/assets/7078459/24016649/3e402f0e-0a8d-11e7-9044-9a8e620fadb7.png)

**Comment by TripSixes** [comment] 2017-03-17 17:01
I've been investigating an issue lately where the screen dimensions are not what they are supposed to be due to the Android navigation bar (on-screen at bottom) is sometimes present and sometimes not when playing Pokemon Go.

Pokemon Go on my phone, Moto Z Droid, seems to randomly pick between going "full screen" (with no nav bar visible), vs other tims where it keeps the nav bar visible and re-draws the Pokemon Go interface accordingly.  For me, GoIV only works properly when the navigation bar is visible.

I have not found a reliable way to get Pokemon Go to either be full screen or nav-bar visible all the time..  If I start up the app and there's no nav bar, my only fix right now is to restart the app until the nav-bar stays on the screen with PoGo open.


The first thing to determine if this is what you're seeing is whether your device has physical nav buttons (outside of the screen) or on-screen soft nav menu.  

Google seems to indicate that your phone does not have physical buttons, so, you might try restarting Pokemon Go  a few times with GoIV running in the background to see if you can get PoGo to launch with the nav-bar visible and see if GoIV detects properly at that time.

**Comment by TripSixes** [comment] 2017-03-17 17:25
Going back and reviewing issue #635, the screenshot provided in that issue is also missing the nav bar, so these issues may be the same root cause.

**Comment by ANDresmar** [comment] 2017-03-18 08:43
Yes that works for me too, showing the nav bar it works properly​, thank you very much
Also it works it quite strange
Maybe if any of you can work on thar it wont and correct it in next update it wont be so strange

**Comment by klikkamongo** [comment] 2017-03-25 15:01
Thanks for reporting this, got the exact same problem on my Umi Plus E, and yes it works with navbar visible.

**Comment by nahojjjen** [comment] 2017-09-30 15:40
This issue should be solved with the scan recalibrate feature released in 4.0.0

If the issue persists, please open a new issue.

**Closed by nahojjjen** 2017-09-30 15:40 UTC
