### ISSUE TITLE
IV button does not show on certain devices

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#347] opened 2016-09-03 06:41 UTC
Bug based on GoIV v.3.1.0, reported on the following devices:

| Phone | Android Version | Remarks |
| --- | --- | --- |
| ZTE Blade V7 | Unknown | NIL |
| Sony Xperia E5 | Android 6.0 | NIL |
| Samsung Galaxy Tab S2 8.0 | Android 6.0.1 | AZ Screen Recorder works |
| Nexus 9 | Android 6.0 & 7.0 | NIL |
| Huawei Y5-II | Android 5.1 | AZ Screen Recorder works <br> Open up one of the 2 gyms, everything freeze then stutter for about a sec and GoIV hangs and do not crash |

**Comment by Blaisorblade** [comment] 2016-09-03 09:55
> Samsung Galaxy Tab S2 8.0

We're not supporting landscape mode—and PoGo itself doesn't run there...

**Comment by DJCrapsody** [comment] 2016-09-03 10:07
@Blaisorblade the device itself is portrait

**Comment by Blaisorblade** [comment] 2016-09-03 10:39
Again: can you install PoGo there? I sure can't on my Nexus 7 2013 with Android 6...

I also won't bet the layout is close enough that screen detection will work there (it's a heuristic after all), but that's up to @farkam135 to say.

We also probably need screenshots of Pokemons from those devices to add support for them.

**Comment by DJCrapsody** [comment] 2016-09-03 11:14
https://www.reddit.com/r/GoIV/comments/505qc2/incompatibility_samsung_table_s2_80_no_overlay/

I can get the user to grab some screenshots of the Pokemons.

**Comment by DJCrapsody** [comment] 2016-09-05 13:24
![Alt Text](http://i.imgur.com/ARBI3QY.png)
![Alt Text](http://i.imgur.com/oOfQOaQ.png)
![Alt Text](http://i.imgur.com/wKr1Ts0.png)

**Comment by Blaisorblade** [comment] 2016-09-09 11:07
Just learned that Zenfone actually dims color when playing with brightness (similar with https://play.google.com/store/apps/details?id=com.haxor&hl=en). That's probably something to check for those devices (if it wasn't asked yet).

**Comment by sarav** [comment] 2016-09-09 14:15
Btw, PoGo and GoIV work perfectly on a Xperia Z2 Tablet.

**Comment by DJCrapsody** [comment] 2016-09-12 23:21
<div class="md"><p>Hi DJCrapsody,</p>

<p>That was one of the first things I checked once I saw it mentioned.  By default, the Tab S2 is set to Adaptive so I set it to basic.  Hasn&#39;t made a difference.  I also individually tested the other modes (the two &quot;AMOLED&quot; modes and the reading mode) to see if any of them changed the issue.   Unfortunately, that does not happen to be the case.</p>

<p>I think I am going to root the tablet as I did my phone and install the Xposed Framework.   There are some modules there that can help in the interim.</p>

<p>If you need any other testing on my end, let me know.</p>
</div>

**Comment by sarav** [comment] 2016-09-13 03:02
Can we just make the app "learn" this too? Just have the user share a screenshot and we'll pick the color from there? Maybe hide it under settings?

**Comment by sarav** [comment] 2016-09-13 03:03
Should be pretty easy to learn it too. We already have the ShareActivity. So, maybe once someone shares a screenshot in battery saver mode, we learn the color from there and remember it as a second option?

**Comment by DJCrapsody** [comment] 2016-09-13 23:02
> Okay I just saw something.  So I tried to reproduce it and it seems to happen again.

> So basically, I was trying to look everywhere in Samsung options to try and see if anything else could possibly be affecting GoIV.  Anyway, I went back to Display and switched to AMOLED Photo.  I tabbed back to Pokemon Go IV (while GoIV being active) and the IV button appeared in the bottom corner  for a split second then disappeared.  I managed to get this to happen a few more times but it disappears to quickly and clicking on the area afterwards does nothing.

> So there does appear to be something in Samsung&#39;s native ROM that is interfering with GoIV.  I just can&#39;t figure out what it is.

Latest update. Seems like display calibration on Samsung devices are screwing with the display. Technically there's a basic mode which turns the screen to use the same calibration as all other devices, but GoIV still wasn't able to scan.

**Comment by Blaisorblade** [comment] 2016-09-14 09:16
Thanks! On @Eremiell's phone we learned that the colors match and the button is still not shown, so there's an extra variable to debug😞

**Comment by Eremiell** [comment] 2016-09-16 06:22
As I don't see it mentioned anywhere, my device (which as mentioned has this bug as well) is [Xiaomi Redmi 3](http://www.gsmarena.com/xiaomi_redmi_3-7862.php). Curiously GoIV worked OK on it before, but now even if I flash older versions down to 2.0, it doesn't for some reason. Might be something in newer PoGo client? Another IV calc draws over PoGo just as before, so it's certainly not blocking all overlays somehow.

**Comment by sarav** [comment] 2016-09-16 06:48
No app downloaded from the play store can actually block another app from doing an overlay (assuming the user gave it permissions). So, I don't think we should ever go down this path of debugging.

> flash older versions down to 2.0

Do you mean older versions of GoIV or the Xiaome Redmi firmware? I'm assuming GoIV?

Couple of questions to try and debug this:

1. Can you confirm that when you are on PoGo you see the "Chromecast" like icon on the notification bar (well, at least the 2 phone I have show those icons when screen is being recorded)? 
2. How did you come to the conclusion that the color matching worked and it was just GoIV overlay that isn't working? I want to hear all the details to make sure there wasn't any bug there.
3. The fact that older versions of GoIV worked and even going back to them doesn't work anymore indicates that some settings changed or you had a firmware upgrade that changed things. Did you update the firmware recently?
4. I remember seeing here or in some chat that it was verified that the colors were correct. How did you do that?
5. How familiar are you with Android Studio and setting up break points and stepping through code?

**Comment by DJCrapsody** [comment] 2016-09-16 06:51
@Eremiell can you try to clear the app data and use ver 2.0?

**Comment by Blaisorblade** [comment] 2016-09-16 08:06
> How did you come to the conclusion that the color matching worked and it was just GoIV overlay that isn't working? I want to hear all the details to make sure there wasn't any bug there.

Logging in the https://github.com/farkam135/GoIV/tree/LoggingBranchForERRORTEST branch confirmed both the pixel values and the actual result of the `shouldShow` variable. The details are unfortunately lost in Discord logs.

Note the code compares also the value of the alpha channel to `0xff` (by using `Color.rgb`), and I suspect we shouldn't, just to be safer. But that can't affect @Eremiell's result because `shouldShow` was logged.

**Comment by Eremiell** [comment] 2016-09-16 12:11
@sarav 

> Can you confirm that when you are on PoGo you see the "Chromecast" like icon on the notification bar (well, at least the 2 phone I have show those icons when screen is being recorded)?

I don't think I ever seen such icon, even back when it worked.

> How did you come to the conclusion that the color matching worked and it was just GoIV overlay that isn't working? I want to hear all the details to make sure there wasn't any bug there.

what @Blaisorblade said

> The fact that older versions of GoIV worked and even going back to them doesn't work anymore indicates that some settings changed or you had a firmware upgrade that changed things. Did you update the firmware recently?

there was no firmware upgrade since I bough the phone, there was a clean stock reflash done at the official service, because the original flash was somehow unstable, but should be the same OS, kernal, etc. I haven't changed anything major in the system before or now and the test suggests, the detection works ok.

> I remember seeing here or in some chat that it was verified that the colors were correct. How did you do that?

what @Blaisorblade said

> How familiar are you with Android Studio and setting up break points and stepping through code?

I'm not much familiar with Android Studio, but I'm debugging very often with gdb, I should be able to do that :P

> Have you tried the Google Now share method to check a pokemon? If not, try that please.

umm, any instructions or link for that? also I probably don't have Google Now as launcher, but something custom from MIUI (I expect).

@DJCrapsody 

> can you try to clear the app data and use ver 2.0?

PoGo app data or GoIV app data or both? but sure, I can.

**Comment by Blaisorblade** [comment] 2016-09-16 12:49
> umm, any instructions or link for that? also I probably don't have Google Now as launcher, but something custom from MIUI (I expect).

Even without Google Now you should be able to share a screenshot to GoIV—and that uses the same code on GoIV side. IIRC I've done it before. That should be equivalent to battery-saver mode—except that it relies on fewer tricks and it should work more easily.

**Comment by Blaisorblade** [comment] 2016-09-16 12:51
BTW: if you want to debug this, I think you want to debug `OcrHelper.scanPokemon`. If that's never run, try to debug its callers (find them with Ctrl-click or Cmd-click on the method name at the definition site).

**Comment by Eremiell** [comment] 2016-09-16 20:22
I can turn on the battery saver mode, but no idea what's the Google Now mode, sorry, if I'm missing something obvious here.

**Comment by sarav** [comment] 2016-09-17 03:12
When you trigger Google Now on Tap, you also get a share option that allows you to share the screenshot of what's on screen to another app. GoIV in this case. You should see GoIV as a share option. Share to that and see if you can get the info dialogs.

**Comment by DJCrapsody** [comment] 2016-09-17 03:18
I'm sure MIUI doesn't have Google Now on Tap.

**Comment by Blaisorblade** [comment] 2016-09-17 09:37
OK, that doesn't really work for me either. I also don't use Google Now on Tap, generally. What I'd expect to work on any phone with any Android version:

- start GoIV
- take a screenshot and open it
- tap the share option from the viewer
- pick GoIV

I get the input dialog with probably correct values, but Check IV crashes. (The crash is really stupid, fixing it).

In fact, I'd want this to work without even starting GoIV first, but it seems I have to start it and specifically in battery saver mode...

**Comment by DJCrapsody** [comment] 2016-09-20 14:25
Updated list.

**Comment by Jesica88** [comment] 2016-09-25 05:32
My lgg5 also doesnt show iv button 😥

**Comment by Eremiell** [comment] 2016-09-26 14:29
Just realized I didn't write it down in here and just mentioned it on Discord. Cleaned both GoIV and PoGo data to no avail, tried to share a screenshot with GoIV and that didn't work either.

**Comment by nahojjjen** [comment] 2017-09-29 21:44
This issue should be fixed by the screen-recalibration feature, which can create pokemon-screen signature pixels dynamically. Any bug with the screen-recalibration should go in a separate issue for easier management.

**Closed by nahojjjen** 2017-09-29 21:44 UTC
Labels: help wanted
